// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVQTLpDzuTNzfvjay-91GcamKZ2DxzgU4',
    appId: '1:528912530435:web:6dd3d5c9e1b410ca3d2236',
    messagingSenderId: '528912530435',
    projectId: 'todofirebase-ddab3',
    authDomain: 'todofirebase-ddab3.firebaseapp.com',
    storageBucket: 'todofirebase-ddab3.appspot.com',
    measurementId: 'G-RXKLPMRZW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx91QBQgN-wh573xfzUl8KAsnuLuVTvUM',
    appId: '1:528912530435:android:1d15934954b44a943d2236',
    messagingSenderId: '528912530435',
    projectId: 'todofirebase-ddab3',
    storageBucket: 'todofirebase-ddab3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUEXvDy37MJ31YPoHFDbnTO2CA59UNxuw',
    appId: '1:528912530435:ios:e2034059df4d75e43d2236',
    messagingSenderId: '528912530435',
    projectId: 'todofirebase-ddab3',
    storageBucket: 'todofirebase-ddab3.appspot.com',
    iosBundleId: 'com.example.flutterToDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUEXvDy37MJ31YPoHFDbnTO2CA59UNxuw',
    appId: '1:528912530435:ios:47304ff7cc7971b73d2236',
    messagingSenderId: '528912530435',
    projectId: 'todofirebase-ddab3',
    storageBucket: 'todofirebase-ddab3.appspot.com',
    iosBundleId: 'com.example.flutterToDoList.RunnerTests',
  );
}
